# This is a basic workflow to help you get started with Actions

name: arm-crosscompilation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  armhf:
    strategy:
      matrix:
        target: [ armv7l-hf-multiplatform ]
        pckg: [ vim, curl ]
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: armhf
          authToken: '${{ secrets.ARMHF }}'
      - run: nix-build default.nix --argstr target ${{ matrix.target }} --argstr pckg ${{ matrix.pckg}} --show-trace --keep-going
  arm64:
    strategy:
      matrix:
        target: [ armv7l-hf-multiplatform ]
        pckg: [ vim, curl ]
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: arm64
          authToken: '${{ secrets.ARM64 }}'
      - run: nix-build default.nix --argstr target ${{ matrix.target }} --argstr pckg ${{ matrix.pckg}} --show-trace --keep-going


