# This is a basic workflow to help you get started with Actions

name: arm-crosscompilation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        target: [ armv7l-hf-multiplatform ]
        package: [ vim, zip, curl, htop, nextdns, tree ]
        include: 
          - target: armv7l-hf-multiplatform
            cache: armhf
          #- target: aarch64-multiplatform
           # cache: arm64
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
            name: ${{ matrix.cache }}
            authToken: '${{ secrets.ARMHF }}'
      - run: nix show-derivation $(nix-instantiate default.nix --argstr target ${{ matrix.target }} --argstr package ${{ matrix.package}})
      - run: nix-build default.nix --argstr target ${{ matrix.target }} --argstr package ${{ matrix.package}} --show-trace --keep-going
